As a part of this i will learn read csv, analyse data ,i will try to find out the unique columns and perform some operations on it. And i will also do a basic plot using matplot lib

Used this dataset from Kaggle https://www.kaggle.com/datasets/mysarahmadbhat/lung-cancer

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("survey lung cancer.csv")
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.LUNG_CANCER.unique()

In [ ]:
df.AGE.unique()

In [ ]:
df.SMOKING.unique()

In [ ]:
df.GENDER.unique()

In [ ]:
df.isnull().sum()

In [ ]:
df.SMOKING.isnull().sum()

In [ ]:
df.AGE.isnull().sum()

In [ ]:
df.LUNG_CANCER.isnull().sum()

<b>Conslusion:<b> i didnt find any of the field with null value

In [ ]:
df=df.dropna()
df.count()

In [ ]:
df.AGE.dropna()
df.AGE.count()

In [ ]:
df.SMOKING.dropna()
df.SMOKING.count()

In [ ]:
df.GENDER.dropna()
df.GENDER.count()

In [ ]:
df.LUNG_CANCER.dropna()
df.LUNG_CANCER.count()

Duplicated records if any

In [ ]:
df.duplicated().sum()

In [ ]:
df.AGE.duplicated().sum()

In [ ]:
df.GENDER.duplicated().sum()

In [ ]:
df.SMOKING.duplicated().sum()

In [ ]:
df.LUNG_CANCER.duplicated().sum()

This will remove if the column has duplicates

In [ ]:
df.drop_duplicates(subset="AGE",keep="first",inplace=True)
df.count()

In [ ]:
df.drop_duplicates(subset="GENDER",keep="first",inplace=True)
df.count()

In [ ]:
df.drop_duplicates(subset="SMOKING",keep="first",inplace=True)
df.count()

In [ ]:
df.drop_duplicates(subset="LUNG_CANCER",keep="first",inplace=True)
df.count()

Now i am doing filtering on M/F

In [ ]:
df[df.GENDER == 'M']

In [ ]:
df[df.GENDER == 'F']

In [ ]:
df

my problem statement : i wanted to see how many F /M involved in smoking, lungs cancer and within which age

In [3]:
df=pd.read_csv("survey lung cancer.csv")
df

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [4]:
df.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [5]:
df.tail()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [6]:
df.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [7]:
df.GENDER.unique()

array(['M', 'F'], dtype=object)

In [8]:
df.AGE.unique()

array([69, 74, 59, 63, 75, 52, 51, 68, 53, 61, 72, 60, 58, 48, 57, 44, 64,
       21, 65, 55, 62, 56, 67, 77, 70, 54, 49, 73, 47, 71, 66, 76, 78, 81,
       79, 38, 39, 87, 46])

In [9]:
df.LUNG_CANCER.unique()

array(['YES', 'NO'], dtype=object)

In [10]:
df.SMOKING.unique()

# Smoking: YES=2 , NO=1

array([1, 2])

In 1st two filters, thinking to keep only smoking & lung cancer rows

In [11]:
df_new = df[(df.SMOKING == 2) & (df.LUNG_CANCER == 'YES')]
df_new.head(2)

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
6,M,52,2,1,1,1,1,2,1,2,2,2,2,1,2,YES

remaining rows, I can groupby (gender, age) and get the count

In [12]:
df_by_gender_age = df.groupby(["GENDER","AGE"]).count()

In [13]:
df_by_gender_age

            SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
GENDER AGE
F      21         1               1        1              1                1
       38         1               1        1              1                1
       44         1               1        1              1                1
       47         2               2        2              2                2
       48         1               1        1              1                1
...             ...             ...      ...            ...              ...
M      75         2               2        2              2                2
       76         2               2        2              2                2
       77         4               4        4              4                4
       78         1               1        1              1                1
       79         1               1        1              1                1

            FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
GENDER AGE
F      21          1         1         1                  1         1
       38          1         1         1                  1         1
       44          1         1         1                  1         1
       47          2         2         2                  2         2
       48          1         1         1                  1         1
...              ...       ...       ...                ...       ...
M      75          2         2         2                  2         2
       76          2         2         2                  2         2
       77          4         4         4                  4         4
       78          1         1         1                  1         1
       79          1         1         1                  1         1

            SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
GENDER AGE
F      21                     1                      1           1
       38                     1                      1           1
       44                     1                      1           1
       47                     2                      2           2
       48                     1                      1           1
...                         ...                    ...         ...
M      75                     2                      2           2
       76                     2                      2           2
       77                     4                      4           4
       78                     1                      1           1
       79                     1                      1           1

            LUNG_CANCER
GENDER AGE
F      21             1
       38             1
       44             1
       47             2
       48             1
...                 ...
M      75             2
       76             2
       77             4
       78             1
       79             1

[70 rows x 14 columns]

u should use df_new in groupby

In [14]:
df_by_gender_age = df_new.groupby(["GENDER","AGE"]).count()

In [15]:
df_by_gender_age

            SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  \
GENDER AGE
F      44         1               1        1              1                1
       47         2               2        2              2                2
       51         5               5        5              5                5
       53         1               1        1              1                1
       54         6               6        6              6                6
       55         4               4        4              4                4
       56         3               3        3              3                3
       58         2               2        2              2                2
       59         2               2        2              2                2
       60         3               3        3              3                3
       61         8               8        8              8                8
       62         4               4        4              4                4
       63         2               2        2              2                2
       64         4               4        4              4                4
       65         2               2        2              2                2
       66         2               2        2              2                2
       67         4               4        4              4                4
       68         1               1        1              1                1
       70         2               2        2              2                2
       71         3               3        3              3                3
       72         2               2        2              2                2
       73         3               3        3              3                3
       74         1               1        1              1                1
       76         1               1        1              1                1
       77         1               1        1              1                1
       78         1               1        1              1                1
M      39         1               1        1              1                1
       48         1               1        1              1                1
       49         1               1        1              1                1
       51         1               1        1              1                1
       52         3               3        3              3                3
       53         1               1        1              1                1
       54         1               1        1              1                1
       55         2               2        2              2                2
       56         5               5        5              5                5
       57         3               3        3              3                3
       58         8               8        8              8                8
       59         3               3        3              3                3
       60         5               5        5              5                5
       61         2               2        2              2                2
       62         6               6        6              6                6
       63         4               4        4              4                4
       64         6               6        6              6                6
       65         3               3        3              3                3
       66         1               1        1              1                1
       67         3               3        3              3                3
       68         3               3        3              3                3
       69         2               2        2              2                2
       70         5               5        5              5                5
       71         2               2        2              2                2
       72         3               3        3              3                3
       74         2               2        2              2                2
       75         2               2        2              2                2
       76         2               2        2              2                2
       77         3               3        3              3                3
       79         1               1        1              1                1

            FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
GENDER AGE
F      44          1         1         1                  1         1
       47          2         2         2                  2         2
       51          5         5         5                  5         5
       53          1         1         1                  1         1
       54          6         6         6                  6         6
       55          4         4         4                  4         4
       56          3         3         3                  3         3
       58          2         2         2                  2         2
       59          2         2         2                  2         2
       60          3         3         3                  3         3
       61          8         8         8                  8         8
       62          4         4         4                  4         4
       63          2         2         2                  2         2
       64          4         4         4                  4         4
       65          2         2         2                  2         2
       66          2         2         2                  2         2
       67          4         4         4                  4         4
       68          1         1         1                  1         1
       70          2         2         2                  2         2
       71          3         3         3                  3         3
       72          2         2         2                  2         2
       73          3         3         3                  3         3
       74          1         1         1                  1         1
       76          1         1         1                  1         1
       77          1         1         1                  1         1
       78          1         1         1                  1         1
M      39          1         1         1                  1         1
       48          1         1         1                  1         1
       49          1         1         1                  1         1
       51          1         1         1                  1         1
       52          3         3         3                  3         3
       53          1         1         1                  1         1
       54          1         1         1                  1         1
       55          2         2         2                  2         2
       56          5         5         5                  5         5
       57          3         3         3                  3         3
       58          8         8         8                  8         8
       59          3         3         3                  3         3
       60          5         5         5                  5         5
       61          2         2         2                  2         2
       62          6         6         6                  6         6
       63          4         4         4                  4         4
       64          6         6         6                  6         6
       65          3         3         3                  3         3
       66          1         1         1                  1         1
       67          3         3         3                  3         3
       68          3         3         3                  3         3
       69          2         2         2                  2         2
       70          5         5         5                  5         5
       71          2         2         2                  2         2
       72          3         3         3                  3         3
       74          2         2         2                  2         2
       75          2         2         2                  2         2
       76          2         2         2                  2         2
       77          3         3         3                  3         3
       79          1         1         1                  1         1

            SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
GENDER AGE
F      44                     1                      1           1
       47                     2                      2           2
       51                     5                      5           5
       53                     1                      1           1
       54                     6                      6           6
       55                     4                      4           4
       56                     3                      3           3
       58                     2                      2           2
       59                     2                      2           2
       60                     3                      3           3
       61                     8                      8           8
       62                     4                      4           4
       63                     2                      2           2
       64                     4                      4           4
       65                     2                      2           2
       66                     2                      2           2
       67                     4                      4           4
       68                     1                      1           1
       70                     2                      2           2
       71                     3                      3           3
       72                     2                      2           2
       73                     3                      3           3
       74                     1                      1           1
       76                     1                      1           1
       77                     1                      1           1
       78                     1                      1           1
M      39                     1                      1           1
       48                     1                      1           1
       49                     1                      1           1
       51                     1                      1           1
       52                     3                      3           3
       53                     1                      1           1
       54                     1                      1           1
       55                     2                      2           2
       56                     5                      5           5
       57                     3                      3           3
       58                     8                      8           8
       59                     3                      3           3
       60                     5                      5           5
       61                     2                      2           2
       62                     6                      6           6
       63                     4                      4           4
       64                     6                      6           6
       65                     3                      3           3
       66                     1                      1           1
       67                     3                      3           3
       68                     3                      3           3
       69                     2                      2           2
       70                     5                      5           5
       71                     2                      2           2
       72                     3                      3           3
       74                     2                      2           2
       75                     2                      2           2
       76                     2                      2           2
       77                     3                      3           3
       79                     1                      1           1

            LUNG_CANCER
GENDER AGE
F      44             1
       47             2
       51             5
       53             1
       54             6
       55             4
       56             3
       58             2
       59             2
       60             3
       61             8
       62             4
       63             2
       64             4
       65             2
       66             2
       67             4
       68             1
       70             2
       71             3
       72             2
       73             3
       74             1
       76             1
       77             1
       78             1
M      39             1
       48             1
       49             1
       51             1
       52             3
       53             1
       54             1
       55             2
       56             5
       57             3
       58             8
       59             3
       60             5
       61             2
       62             6
       63             4
       64             6
       65             3
       66             1
       67             3
       68             3
       69             2
       70             5
       71             2
       72             3
       74             2
       75             2
       76             2
       77             3
       79             1

now draw some plot

In [24]:
plt.plot(df_by_gender_age)
plt.title("LUNG_CANCER Analysis")
plt.xlabel("LUNG_CANCER")
plt.ylabel("AGE")

TypeError: 'value' must be an instance of str or bytes, not a tuple